version: 2
updates:
  - package-ecosystem: "npm"  # or "pip", "maven", etc.
    directory: "/"  # Location of your package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"